# Generated by Django 4.1.6 on 2023-02-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwd',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
