# Generated by Django 4.1.6 on 2023-02-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(max_length=1000),
        ),
    ]
