# Generated by Django 4.1.6 on 2023-02-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_food_quantity_alter_food_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
