# Generated by Django 4.1.6 on 2023-02-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_alter_food_price_alter_food_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(to='api.food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(max_length=1000),
        ),
    ]
